database:
  pgql:
    log_queries: true
    timeout_seconds: 1
    dsn: ""
  mongo:
    dsn: ""

server:
  port: 8080
  debug: true
  read_timeout_seconds: 1
  write_timeout_seconds: 1
  gin_mode: release

jwt:
  secret: nguy3nd3ptr4i
  duration_minutes: 15
  refresh_duration_minutes: 15
  max_refresh_minutes: 1440
  signing_algorithm: HS256

swagger:
  min_password_strength: 1
  swagger_ui_path: assets/swaggerui

log:
  enable_console: true
  console_level: info
  console_json_format: true
  enable_file: true
  file_level: info
  file_json_format: true
